#### Name :- Shivam Pal || Enroll :- 2021MSBDA038

# Assignment : 1

### Que :-  Write a program in python to compute the eigen values and eigen vectors of any dataset.

### Importing Libraries

In [4]:
import numpy as np
import pandas as pd

### Importing DataSet

In [5]:
ds = pd.read_csv("https://raw.githubusercontent.com/AdiPersonalWorks/Random/master/student_scores%20-%20student_scores.csv")

### Now, Visualizing the DataSet

In [6]:
DATA = ds.head(10)
DATA

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30
5    1.5      20
6    9.2      88
7    5.5      60
8    8.3      81
9    2.7      25

In [7]:
ds.shape

(25, 2)

### Converting DataSet into the Matrix form

In [8]:
Array = DATA.to_numpy()
Array

array([[ 2.5, 21. ],
       [ 5.1, 47. ],
       [ 3.2, 27. ],
       [ 8.5, 75. ],
       [ 3.5, 30. ],
       [ 1.5, 20. ],
       [ 9.2, 88. ],
       [ 5.5, 60. ],
       [ 8.3, 81. ],
       [ 2.7, 25. ]])

In [9]:
DATA.shape

(10, 2)

### For Reduce the shape of matrix, multiply the original matrix with thier transpose matrix.

In [10]:
matrix = Array
matrix.shape

(10, 2)

In [11]:
trans_matrix = matrix.transpose()
trans_matrix

array([[ 2.5,  5.1,  3.2,  8.5,  3.5,  1.5,  9.2,  5.5,  8.3,  2.7],
       [21. , 47. , 27. , 75. , 30. , 20. , 88. , 60. , 81. , 25. ]])

In [12]:
trans_matrix.shape

(2, 10)

In [13]:
reduced_matrix = np.dot(trans_matrix,matrix)
reduced_matrix

array([[  320.32,  3030.5 ],
       [ 3030.5 , 28834.  ]])

In [14]:
reduced_matrix.shape

(2, 2)

In [15]:
W = np.linalg.eig(reduced_matrix)
W

(array([1.78978050e+00, 2.91525302e+04]),
 array([[-0.99452149, -0.1045323 ],
        [ 0.1045323 , -0.99452149]]))

### Eigen Value and Eigen Vectors are :-

In [16]:
print("Eigen_Val :",W[0])

Eigen_Val : [1.78978050e+00 2.91525302e+04]


In [17]:
print("Eigen_Vec :",W[1 :])

Eigen_Vec : (array([[-0.99452149, -0.1045323 ],
       [ 0.1045323 , -0.99452149]]),)


#                   -----------------                 THANK YOU             ------------------