#### Name :- Shivam Pal || Enroll :- 2021MSBDA038
    

# Assignment : 2

## Que :-  Compute eigen values and eigen vectors and SVD of any dataset.

### Importing Libraries

In [383]:
import numpy as np
import pandas as pd

### Importing DataSet

In [384]:
ds = pd.read_csv("https://raw.githubusercontent.com/AdiPersonalWorks/Random/master/student_scores%20-%20student_scores.csv")

### Now, Visualizing the DataSet

In [385]:
DATA = ds.head(10)
DATA

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30
5    1.5      20
6    9.2      88
7    5.5      60
8    8.3      81
9    2.7      25

In [386]:
ds.shape

(25, 2)

### Converting DataSet into the Matrix form

In [387]:
Array = DATA.to_numpy()
Array

array([[ 2.5, 21. ],
       [ 5.1, 47. ],
       [ 3.2, 27. ],
       [ 8.5, 75. ],
       [ 3.5, 30. ],
       [ 1.5, 20. ],
       [ 9.2, 88. ],
       [ 5.5, 60. ],
       [ 8.3, 81. ],
       [ 2.7, 25. ]])

In [388]:
DATA.shape

(10, 2)

### For Reduce the shape of matrix, multiply the original matrix with thier transpose matrix.

In [389]:
matrix = Array
matrix.shape

(10, 2)

In [390]:
trans_matrix = matrix.transpose()
trans_matrix

array([[ 2.5,  5.1,  3.2,  8.5,  3.5,  1.5,  9.2,  5.5,  8.3,  2.7],
       [21. , 47. , 27. , 75. , 30. , 20. , 88. , 60. , 81. , 25. ]])

In [391]:
trans_matrix.shape

(2, 10)

In [392]:
reduced_matrix = np.dot(trans_matrix,matrix)
reduced_matrix

array([[  320.32,  3030.5 ],
       [ 3030.5 , 28834.  ]])

In [393]:
reduced_matrix.shape

(2, 2)

In [394]:
W = np.linalg.eig(reduced_matrix)
W

(array([1.78978050e+00, 2.91525302e+04]),
 array([[-0.99452149, -0.1045323 ],
        [ 0.1045323 , -0.99452149]]))

### Eigen Value and Eigen Vectors are :-

In [395]:
ev, D = W
print("Eigen_Val =",ev)
print("Eigen_Val =",D)

Eigen_Val = [1.78978050e+00 2.91525302e+04]
Eigen_Val = [[-0.99452149 -0.1045323 ]
 [ 0.1045323  -0.99452149]]


# Now, STEPS for compute SVD :

In [396]:
D[:,0]      #Use for convert convert column vector as a row vector

array([-0.99452149,  0.1045323 ])

### Normalizing all eigen vectors

In [397]:
from numpy.linalg import norm
x0 = matrix@D[:,0]/norm(matrix@D[:,0])
x1 = matrix@D[:,1]/norm(matrix@D[:,1])

### An Orthogonal Matrix 'U' is

In [398]:
U = np.array([x0,x1]).T

### A Diagonal matrix 'V' is

In [399]:
V = np.round(U.T@matrix@D, decimals = 6)
V

array([[  1.337827,  -0.      ],
       [ -0.      , 170.74112 ]])

### Now SVD is

In [400]:
U@V@D.T

array([[ 2.50000004, 20.99999994],
       [ 5.10000001, 46.99999987],
       [ 3.20000005, 26.99999992],
       [ 8.50000008, 74.99999978],
       [ 3.50000005, 29.99999991],
       [ 1.4999999 , 19.99999996],
       [ 9.19999997, 87.99999976],
       [ 5.49999985, 59.99999985],
       [ 8.29999994, 80.99999978],
       [ 2.7       , 24.99999993]])

In [401]:
D

array([[-0.99452149, -0.1045323 ],
       [ 0.1045323 , -0.99452149]])

In [402]:
def printPrincipalDiagonal(V, n):
 
    print("V = ", end = "")
 
    for i in range(n):
         
        print(V[i][i], end = ", ")
 
    print()
n = 2
printPrincipalDiagonal(V, n)

V = 1.337827, 170.74112, 


In [403]:
U

array([[-0.21761063, -0.12384997],
       [-0.11888033, -0.27688482],
       [-0.2691653 , -0.15922693],
       [-0.4585869 , -0.44205893],
       [-0.25777334, -0.17688479],
       [ 0.44763931, -0.11741301],
       [ 0.03680976, -0.51820902],
       [ 0.59953208, -0.35285125],
       [ 0.15890569, -0.47688488],
       [-0.05374419, -0.14727135]])

## Now Check my values by importing SVD function 

In [404]:
from numpy.linalg import svd
s,v,d = svd(matrix)
print(svd(matrix))

(array([[-0.12384997, -0.21761063, -0.16227485, -0.45000613, -0.1801972 ,
        -0.11850856, -0.52650114, -0.35747318, -0.48429283, -0.14974238],
       [-0.27688482, -0.11888033, -0.26455698, -0.45037612, -0.25330872,
         0.44077976,  0.03731596,  0.59075659,  0.15738655, -0.05258102],
       [-0.15922693, -0.2691653 ,  0.92658025, -0.14294431, -0.0728633 ,
         0.08213756, -0.04641958,  0.08955697, -0.01634684, -0.02673401],
       [-0.44205893, -0.4585869 , -0.13996927,  0.70334559, -0.14235725,
         0.10255758, -0.16482939,  0.07071784, -0.11186645, -0.06729082],
       [-0.17688479, -0.25777334, -0.07243829, -0.14448228,  0.92761804,
         0.07332077, -0.0567039 ,  0.07407181, -0.02765723, -0.0287087 ],
       [-0.11741301,  0.44763931,  0.08879598,  0.11884947,  0.0804042 ,
         0.77973271, -0.1147014 , -0.33215776, -0.16084939, -0.00420272],
       [-0.51820902,  0.03680976, -0.03701278, -0.14839583, -0.04763711,
        -0.12943493,  0.7352381 , -0.2710925

# Now comparing the value of "UVD" by "svd" 
Where,                
"UVD" value is find without using inbuilt function               
"svd" value is find by using inbuilt function svd()

In [405]:
#comparing 'V' & 'v'
printPrincipalDiagonal(V, n) 
print("v = ",v)


V = 1.337827, 170.74112, 
v =  [170.74112047   1.33782678]


In [406]:
#comparing 'D' & 'd'
print("D = ",D)
print("")
print("d = ",d)

D =  [[-0.99452149 -0.1045323 ]
 [ 0.1045323  -0.99452149]]

d =  [[-0.1045323  -0.99452149]
 [-0.99452149  0.1045323 ]]


In [407]:
#comparing 'U' & 's'
print("U = ",U)
print("")
print("s = ",s)

U =  [[-0.21761063 -0.12384997]
 [-0.11888033 -0.27688482]
 [-0.2691653  -0.15922693]
 [-0.4585869  -0.44205893]
 [-0.25777334 -0.17688479]
 [ 0.44763931 -0.11741301]
 [ 0.03680976 -0.51820902]
 [ 0.59953208 -0.35285125]
 [ 0.15890569 -0.47688488]
 [-0.05374419 -0.14727135]]

s =  [[-0.12384997 -0.21761063 -0.16227485 -0.45000613 -0.1801972  -0.11850856
  -0.52650114 -0.35747318 -0.48429283 -0.14974238]
 [-0.27688482 -0.11888033 -0.26455698 -0.45037612 -0.25330872  0.44077976
   0.03731596  0.59075659  0.15738655 -0.05258102]
 [-0.15922693 -0.2691653   0.92658025 -0.14294431 -0.0728633   0.08213756
  -0.04641958  0.08955697 -0.01634684 -0.02673401]
 [-0.44205893 -0.4585869  -0.13996927  0.70334559 -0.14235725  0.10255758
  -0.16482939  0.07071784 -0.11186645 -0.06729082]
 [-0.17688479 -0.25777334 -0.07243829 -0.14448228  0.92761804  0.07332077
  -0.0567039   0.07407181 -0.02765723 -0.0287087 ]
 [-0.11741301  0.44763931  0.08879598  0.11884947  0.0804042   0.77973271
  -0.1147014  -0.33

#                   -----------------                 THANK YOU             ------------------